export const products = [
  {
    id: 1,
    name: "Red Bench",
    category: "People",
    price: 3.89,
    currency: "USD",
    dimmentions: {
      width: 3933,
      height: 5891,
    },
    size: 10000,
    image: {
      src: "https://images.pexels.com/photos/9507099/pexels-photo-9507099.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Black and White Floral Padded Brown Wooden Framed Armchair",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    id: 2,
    name: "Person Facing Laptop",
    category: "People",
    price: 54.89,
    currency: "USD",
    dimmentions: {
      width: 2475,
      height: 2375,
    },
    size: 2960,
    image: {
      src: "https://images.pexels.com/photos/57690/pexels-photo-57690.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Person Sitting Facing Laptop Computer With Sketch Pad",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    id: 3,
    name: "Woman Using Camera",
    category: "People",
    price: 23.89,
    currency: "USD",
    dimmentions: {
      width: 5904,
      height: 4000,
    },
    size: 16190,
    image: {
      src: "https://images.pexels.com/photos/610293/pexels-photo-610293.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Woman Leaning Back on Tree Trunk Using Black Dslr Camera during Day",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    id: 4,
    name: "Black bike",
    category: "Transport",
    price: 14.89,
    currency: "USD",
    dimmentions: {
      width: 3911,
      height: 2500,
    },
    size: 2300,
    image: {
      src: "https://images.pexels.com/photos/276517/pexels-photo-276517.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Black Fixed-gear Bike Beside Wall",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    id: 5,
    name: "Black Film Camera",
    category: "Lifestyle",
    price: 343.89,
    currency: "USD",
    dimmentions: {
      width: 6014,
      height: 4015,
    },
    size: 20900,
    image: {
      src: "https://images.pexels.com/photos/733853/pexels-photo-733853.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Black and Silver Film Camera on Brown Wooden Surface",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    id: 6,
    name: "Cooed Food",
    category: "Food",
    price: 7.89,
    currency: "USD",
    dimmentions: {
      width: 5466,
      height: 3245,
    },
    size: 1700,
    image: {
      src: "https://images.pexels.com/photos/2103949/pexels-photo-2103949.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Cooed Food",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    id: 7,
    name: "Happy friends",
    category: "Lifestyle",
    price: 31.89,
    currency: "USD",
    dimmentions: {
      width: 3233,
      height: 4891,
    },
    size: 4690,
    image: {
      src: "https://images.pexels.com/photos/4553618/pexels-photo-4553618.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Happy friends on camper van roof",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    id: 8,
    name: "Man Dunking the Ball",
    category: "People",
    price: 67.89,
    currency: "USD",
    dimmentions: {
      width: 4912,
      height: 3211,
    },
    size: 2231,
    image: {
      src: "https://images.pexels.com/photos/163452/basketball-dunk-blue-game-163452.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Man Dunking the Ball",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    id: 9,
    name: "Palm Tree Planted Near Pool",
    category: "Lifestyle",
    price: 322.89,
    currency: "USD",
    dimmentions: {
      width: 7200,
      height: 4000,
    },
    size: 7130,
    image: {
      src: "https://images.pexels.com/photos/261101/pexels-photo-261101.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Palm Tree Planted Near Pool",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    id: 10,
    name: "People Drinking Coffee",
    category: "Food",
    price: 3.89,
    currency: "USD",
    dimmentions: {
      width: 3933,
      height: 5891,
    },
    size: 10000,
    image: {
      src: "https://images.pexels.com/photos/3361170/pexels-photo-3361170.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "People With Four Drinking Glasses Of Coffee While Making A Toast",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    id: 11,
    name: "Starry Sky",
    category: "Landmarks",
    price: 333.89,
    currency: "USD",
    dimmentions: {
      width: 4015,
      height: 4015,
    },
    size: 12960,
    image: {
      src: "https://images.pexels.com/photos/4417069/pexels-photo-4417069.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Anonymous tourist taking photo of starry sky while standing on road",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    id: 12,
    name: "Health Workers",
    category: "People",
    price: 26.89,
    currency: "USD",
    dimmentions: {
      width: 5600,
      height: 4500,
    },
    size: 6800,
    image: {
      src: "https://images.pexels.com/photos/3957987/pexels-photo-3957987.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Health Workers Wearing Face Mask",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    id: 13,
    name: "Clear Wine Glass",
    category: "Food",
    price: 47.89,
    currency: "USD",
    dimmentions: {
      width: 4000,
      height: 6000,
    },
    size: 9030,
    image: {
      src: "https://images.pexels.com/photos/4099306/pexels-photo-4099306.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Person Holding Clear Wine Glass",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    id: 14,
    name: "Black Ship",
    category: "Transport",
    price: 78.89,
    currency: "USD",
    dimmentions: {
      width: 2800,
      height: 3000,
    },
    size: 4500,
    image: {
      src: "https://images.pexels.com/photos/1095814/pexels-photo-1095814.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Shallow Focus Photography of Black Ship",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    id: 15,
    name: "Light Trails",
    category: "Transport",
    price: 322,
    currency: "USD",
    dimmentions: {
      width: 6000,
      height: 4000,
    },
    size: 5600,
    image: {
      src: "https://images.pexels.com/photos/315938/pexels-photo-315938.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Light Trails on Highway at Night",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    id: 16,
    name: "Black and Oragne Cat",
    category: "Pets",
    price: 311.89,
    currency: "USD",
    dimmentions: {
      width: 2670,
      height: 4000,
    },
    size: 5170,
    image: {
      src: "https://images.pexels.com/photos/7726100/pexels-photo-7726100.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "A Black and Orange Tabby Cat Lying Together on Gray Textile",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    id: 17,
    name: "Egg Balloon",
    category: "Food",
    price: 93.89,
    currency: "USD",
    dimmentions: {
      width: 7742,
      height: 6690,
    },
    size: 7350,
    image: {
      src: "https://images.pexels.com/photos/14038038/pexels-photo-14038038.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Close Up Photo of Dish on White Ceramic Plate",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    id: 18,
    name: "Man",
    category: "People",
    price: 100,
    currency: "USD",
    dimmentions: {
      width: 4769,
      height: 3179,
    },
    size: 8190,
    image: {
      src: "https://images.pexels.com/photos/670720/pexels-photo-670720.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Person Standing Near Lake",
    },
    bestseller: false,
    featured: false,
    details: null,
  },
  {
    id: 19,
    name: "Architecture",
    category: "Landmarks",
    price: 101,
    currency: "USD",
    dimmentions: {
      width: 6016,
      height: 4016,
    },
    size: 1220,
    image: {
      src: "https://images.pexels.com/photos/911758/pexels-photo-911758.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Long Exposure Photography White Dome Building Interior",
    },
    bestseller: true,
    featured: false,
    details: null,
  },
  {
    id: 20,
    name: "Samurai King Restling",
    category: "Pets",
    price: 101,
    currency: "USD",
    image: {
      src: "https://images.pexels.com/photos/4032590/pexels-photo-4032590.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "A Roaring Lion",
    },
    bestseller: false,
    featured: true,
    details: {
      dimmentions: {
        width: 4704,
        height: 5466,
      },
      size: 18,
      description:
        "So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely scrambled part of Cicero's De Finibus in order to provide placeholder text to mockup various fonts for a type specimen book.So how did the classical Latin become so incoherent? According to McClintock, a 15th century typesetter likely scrambled part of Cicero's De Finibus in order to provide placeholder text to mockup various fonts for a type specimen book. So how did the classical Latin become so incoherent? According to McClintock.",
      recommendations: [
        {
          src: "https://images.pexels.com/photos/911758/pexels-photo-911758.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          alt: "Long Exposure Photography White Dome Building Interior",
        },
        {
          src: "https://images.pexels.com/photos/670720/pexels-photo-670720.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          alt: "Person Standing Near Lake",
        },
        {
          src: "https://images.pexels.com/photos/14038038/pexels-photo-14038038.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
          alt: "Close Up Photo of Dish on White Ceramic Plate",
        },
      ],
    },
  },
];
